export const ARTISTS = [
  {
    name: "Joaquín Sabina",
    imageUrl: "/images/artists/sabina.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/jsabinaoficial/",
  },
  {
    name: "Pimpinela",
    imageUrl: "/images/artists/pimpinela.png",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/duopimpinela/?hl=es-la",
  },
  {
    name: "Serú Girán",
    imageUrl: "/images/artists/seru.png",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/serugiranok/?hl=es-la",
  },
  {
    name: "Q'Lokura",
    imageUrl: "/images/artists/lokura.png",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/qlokuraok/?hl=es",
  },
  {
    name: "David Lebón",
    imageUrl: "/images/artists/lebon.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/lebondavidok/?hl=es",
  },
  {
    name: "Rebord",
    imageUrl: "/images/artists/rebord.png",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/tomasrebord/?hl=es-la",
  },
  {
    name: "Caballeros de la Quema",
    imageUrl: "/images/artists/caballeros.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/caballerosdelquema",
  },
  {
    name: "La banda Sabinera",
    imageUrl: "/images/artists/sabinera.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/labandasabinera",
  },
  {
    name: "G Sony",
    imageUrl: "/images/artists/sony.png",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/gsonymusic",
  },
  {
    name: "La Pepa Brizuela",
    imageUrl: "/images/artists/brizuela.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/javierlapepabrizuela",
  },
  {
    name: "Patricia Sosa",
    imageUrl: "/images/artists/patricia.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/patriciasosaoficial",
  },
  {
    name: "Palito Ortega",
    imageUrl: "/images/artists/palito.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/palitoortegaoficial",
  },
  {
    name: "Juan Fuentes",
    imageUrl: "/images/artists/fuentes.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/eljuanfuentes",
  },
  {
    name: "Lucho Arrieta",
    imageUrl: "/images/artists/arrieta.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/luchoarrietaoficial",
  },
  {
    name: "Sergio Dalma",
    imageUrl: "/images/artists/dalma.png",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/sergiodalmaoficial",
  },
  {
    name: "Patito Feo",
    imageUrl: "/images/artists/patito.jpg",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/patitofeoenvivo",
  },
  {
    name: "Tutankamon",
    imageUrl: "/images/artists/tutan.png",
    spotifyUrl: "https://spotify.com",
    instagramUrl: "https://www.instagram.com/tutankamonok",
  },
] as const;
